jdbc:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://121.4.53.107:3306/springboot_test
  username: root
  password: wahahah

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.4.53.107:3306/springboot_test
    username: root
    password: wahahah
  redis:
    host: localhost
    port: 6379

# tomcat端口,映射到xxxProperty属性对象的相关字段中.
server:
  port: 80

#日志记录级别
logging:
  level:
    com.itheima: debug
    org.springframework: info

# mybatis映射器
mybatis:
  # 实体类别名包路径
  type-aliases-package: com.itheima.pojo
  # 映射文件路径
  # mapper-locations: classpath:mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

itheima:
  url: http://www.itheima.com